# Generated by Django 3.2.6 on 2021-09-02 05:09

import colorfield.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type_name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChoosableOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_in_en', models.CharField(max_length=100)),
                ('name_in_nl', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100)),
                ('color_code', colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18)),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_in_en', models.CharField(max_length=100)),
                ('model_in_en', models.CharField(max_length=100)),
                ('brand_in_nl', models.CharField(max_length=100)),
                ('model_in_nl', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('Description_in_en', models.TextField()),
                ('Description_in_nl', models.TextField()),
                ('wtlp_range', models.IntegerField()),
                ('additional_percentage', models.IntegerField()),
                ('battery_capacity', models.IntegerField()),
                ('tax_value', models.IntegerField()),
                ('expected_delivery_time', models.IntegerField()),
                ('Category', models.IntegerField()),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('created_by', models.CharField(max_length=50)),
                ('car_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.cartype')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.vehiclecolor')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
