# Generated by Django 3.2.6 on 2021-09-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_vehicledata_expected_delivery_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicledata',
            old_name='color',
            new_name='color_id',
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='Description_in_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='Description_in_nl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
