# Generated by Django 3.2.6 on 2021-09-03 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20210902_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledata',
            name='color_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='application.vehiclecolor'),
        ),
    ]
