# Generated by Django 3.2.6 on 2021-09-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20210906_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclecolor',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='vehicledata',
            name='color_id',
        ),
        migrations.AddField(
            model_name='vehiclecolor',
            name='b',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecolor',
            name='g',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecolor',
            name='hex_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecolor',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='vehiclecolor',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='vehiclecolor',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='vehiclecolor',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='vehiclecolor',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='vehiclecolor',
            name='r',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclecolor',
            name='color_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
