# Generated by Django 3.2.6 on 2021-09-06 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20210906_1200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChoosableOption',
        ),
        migrations.DeleteModel(
            name='VehicleColor',
        ),
        migrations.RemoveField(
            model_name='vehicledata',
            name='car_type_id',
        ),
        migrations.DeleteModel(
            name='CarType',
        ),
        migrations.DeleteModel(
            name='VehicleData',
        ),
    ]
