# Generated by Django 3.2.6 on 2021-09-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_auto_20210930_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors_ev',
            name='img1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colors_ev',
            name='img2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colors_ev',
            name='img3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colors_ev',
            name='img4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colors_ev',
            name='img5',
            field=models.URLField(blank=True, null=True),
        ),
    ]
