# Generated by Django 3.2.6 on 2021-09-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20210930_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='electric_vehicles',
            name='Manufacturer_specification_km_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electric_vehicles',
            name='charging_speed_fast_charging_kwh',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electric_vehicles',
            name='fast_charge_ten_to_eigthy_percent_in_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electric_vehicles',
            name='fuel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electric_vehicles',
            name='heat_pump',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electric_vehicles',
            name='km_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electric_vehicles',
            name='lease_ex_fuel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electric_vehicles',
            name='lease_incl_fuel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electric_vehicles',
            name='ten_minutes_of_fast_charging_is_km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electric_vehicles',
            name='towbar_contribution',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electric_vehicles',
            name='towbar_explanation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='electric_vehicles',
            name='version',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
