# Generated by Django 3.2.6 on 2021-10-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_auto_20211001_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electric_vehicles',
            name='battery_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
