# Generated by Django 3.2.6 on 2021-10-01 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_alter_electric_vehicles_battery_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftevuploadexcel',
            name='ev_file',
            field=models.FileField(blank=True, null=True, upload_to='excel', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ods', 'xlr', 'xlw', 'xla', 'xlam', 'xml', 'xml', 'xls', 'xlsx', 'xlsm', 'xlsb', 'xltx', 'xltm'])]),
        ),
    ]
