# Generated by Django 3.2.6 on 2021-10-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_alter_shiftevuploadexcel_ev_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='electric_vehicles',
            name='longr_range_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='electric_vehicles',
            name='brand_en',
            field=models.CharField(default='Fiat', max_length=200),
        ),
        migrations.AlterField(
            model_name='electric_vehicles',
            name='model_en',
            field=models.CharField(default='500e', max_length=200),
        ),
    ]
