# Generated by Django 3.2.6 on 2021-10-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_auto_20211004_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electric_vehicles',
            name='brand_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='electric_vehicles',
            name='model_en',
            field=models.CharField(max_length=200),
        ),
    ]
