# Generated by Django 3.2.6 on 2021-10-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_auto_20211004_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electric_vehicles',
            old_name='longr_range_user',
            new_name='longr_range_vehicles',
        ),
    ]
