# Generated by Django 3.2.6 on 2021-10-05 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_rename_longr_range_user_electric_vehicles_longr_range_vehicles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electric_vehicles',
            old_name='longr_range_vehicles',
            new_name='long_range_vehicles',
        ),
    ]
