# Generated by Django 3.2.6 on 2021-10-05 10:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_remove_electric_vehicles_long_range_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='electric_vehicles',
            name='long_range_vehicles',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=[1, 2], size=None),
        ),
    ]
