# Generated by Django 3.2.6 on 2021-10-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0031_remove_electric_vehicles_long_range_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='electric_vehicles',
            name='long_range_vehicles',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
