# Generated by Django 3.2.6 on 2021-10-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_electric_vehicles_long_range_vehicles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electric_vehicles',
            old_name='long_range_vehicles',
            new_name='long_range_vehicles_category',
        ),
    ]
