# Generated by Django 3.2.6 on 2021-10-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0033_rename_long_range_vehicles_electric_vehicles_long_range_vehicles_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electric_vehicles',
            name='long_range_vehicles_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
