# Generated by Django 3.2.6 on 2021-10-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0034_alter_electric_vehicles_long_range_vehicles_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electric_vehicles',
            name='tax_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
