# Generated by Django 3.2.6 on 2021-10-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0036_remove_electric_vehicles_long_range_vehicles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='electric_vehicles',
            name='long_range_vehicles_category',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
