# Generated by Django 3.2.6 on 2021-10-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0038_alter_electric_vehicles_long_range_vehicles_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electric_vehicles',
            name='long_range_vehicles_category',
        ),
    ]
