# Generated by Django 3.2.6 on 2021-10-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0042_alter_electric_vehicles_expected_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electric_vehicles',
            name='battery_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
