# Generated by Django 3.2.6 on 2021-10-09 08:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0044_rename_wtlp_range_electric_vehicles_wltp_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarVsBasicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_en', models.CharField(max_length=200)),
                ('brand_nl', models.CharField(max_length=200)),
                ('model_en', models.CharField(max_length=200)),
                ('model_nl', models.CharField(max_length=200)),
                ('color_en', models.CharField(max_length=200)),
                ('color_nl', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, max_length=200, null=True)),
                ('licence_plate', models.CharField(max_length=200, unique=True)),
                ('transition', models.CharField(max_length=100)),
                ('pitch_en', models.TextField(default=None)),
                ('pitch_nl', models.TextField(default=None)),
                ('doors', models.IntegerField()),
                ('category', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('construction_year', models.IntegerField()),
                ('fuel', models.FloatField()),
                ('price', models.FloatField()),
                ('ispublished', models.BooleanField(default=False)),
                ('long_range_vehicles_category', models.CharField(blank=True, max_length=10, null=True)),
                ('img1', models.URLField(blank=True, null=True)),
                ('img2', models.URLField(blank=True, null=True)),
                ('img3', models.URLField(blank=True, null=True)),
                ('img4', models.URLField(blank=True, null=True)),
                ('img5', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarVsTaxData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_value', models.FloatField()),
                ('first_registration', models.IntegerField()),
                ('power_pk', models.IntegerField()),
                ('power_kw', models.IntegerField()),
                ('co2_emission_wtlp', models.IntegerField()),
                ('co2_emission_nedc', models.IntegerField()),
                ('tax_addition', models.FloatField()),
                ('energie_label', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax', to='application.carvsbasicdata')),
            ],
        ),
        migrations.CreateModel(
            name='CarVsOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_version', models.CharField(max_length=100)),
                ('trailer_hitch', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('navigation', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('air_conditioning', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='application.carvsbasicdata')),
            ],
        ),
        migrations.CreateModel(
            name='carVsContractDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(default=datetime.date(2021, 10, 9))),
                ('end_date', models.DateField()),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('lease_amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='application.carvsbasicdata')),
            ],
        ),
    ]
