# Generated by Django 3.2.6 on 2021-10-09 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0046_alter_carvscontractdetails_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carvscontractdetails',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 9, 8, 57, 58, 334547)),
        ),
    ]
