# Generated by Django 3.2.6 on 2021-10-10 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0049_alter_electric_vehicles_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carvscontractdetails',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 10, 10)),
        ),
        migrations.AlterField(
            model_name='choosable_options_ev',
            name='option_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
