# Generated by Django 3.2.6 on 2021-10-11 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0051_alter_carvscontractdetails_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electric_vehicles',
            name='long_range_vehicles_category',
        ),
    ]
