# Generated by Django 3.2.6 on 2021-10-12 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0054_auto_20211011_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carvscontractdetails',
            name='car_details',
        ),
        migrations.RemoveField(
            model_name='carvsoptions',
            name='car_details',
        ),
        migrations.RemoveField(
            model_name='carvstaxdata',
            name='car_details',
        ),
        migrations.DeleteModel(
            name='CarVsBasicData',
        ),
        migrations.DeleteModel(
            name='carVsContractDetails',
        ),
        migrations.DeleteModel(
            name='CarVsOptions',
        ),
        migrations.DeleteModel(
            name='CarVsTaxData',
        ),
    ]
