# Generated by Django 3.2.6 on 2021-10-12 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0057_auto_20211012_0620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarVsBasicData',
            new_name='vs_vehicles',
        ),
    ]
