# Generated by Django 3.2.6 on 2021-10-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0058_rename_carvsbasicdata_vs_vehicles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vs_vehicles',
        ),
    ]
