# Generated by Django 3.2.6 on 2021-10-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0060_vs_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vs_vehicles',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vs_vehicles',
            name='first_registration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vs_vehicles',
            name='power_kw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vs_vehicles',
            name='power_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vs_vehicles',
            name='tax_addition',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vs_vehicles',
            name='tax_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
