# Generated by Django 3.2.6 on 2021-10-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0061_auto_20211012_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vs_vehicles',
            name='pitch_en',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vs_vehicles',
            name='pitch_nl',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
