# Generated by Django 3.2.6 on 2021-10-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0064_auto_20211020_0613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vs_vehicles',
            old_name='brand',
            new_name='b',
        ),
        migrations.RenameField(
            model_name='vs_vehicles',
            old_name='model',
            new_name='m',
        ),
    ]
