# Generated by Django 3.2.6 on 2021-10-20 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0065_auto_20211020_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vs_vehicles',
            name='b',
        ),
        migrations.RemoveField(
            model_name='vs_vehicles',
            name='m',
        ),
    ]
