# Generated by Django 3.2.6 on 2021-10-20 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0066_auto_20211020_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vs_vehicles',
            old_name='brand_en',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='vs_vehicles',
            old_name='model_en',
            new_name='model',
        ),
    ]
