# Generated by Django 3.2.6 on 2021-10-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0068_auto_20211020_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vs_vehicles',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
