# Generated by Django 3.2.6 on 2021-10-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0069_alter_vs_vehicles_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='vs_vehicles_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_pdf', models.FileField(upload_to='Agreements/')),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
