# Generated by Django 3.2.6 on 2021-10-28 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0070_vs_vehicles_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vs_vehicles_order',
            new_name='ev_vehicles_order',
        ),
    ]
