# Generated by Django 3.2.6 on 2021-10-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0071_rename_vs_vehicles_order_ev_vehicles_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ev_vehicles_order',
            name='agreement_pdf',
            field=models.FileField(upload_to='agreements/'),
        ),
    ]
